const mockProducts = [{
    id : 1,
    img: "../Balanced.jpg",
    title : "Alimento Balanceado",
    category: 'perro',
    brand : "Balanced", 
    price : 4550,
    kg : 20,
    stock : 20,
    initial : 1,
},
{
    id : 2,
    img: "../Deleita.jpg",
    title : "Alimento Balanceado",
    category: 'perro',
    brand : "Deleita", 
    price : 3570,
    kg : 15,
    stock : 50,
    initial : 1,
},
{
    id : 3,
    img: "../Advance.jpg",
    title : "Alimento Balanceado",
    category: 'perro',
    brand : "Advance", 
    price : 5600,
    kg : 22,
    stock : 100,
    initial : 1,  
},
{
    id : 4,
    img: "../NutriqueGato.jpg",
    title : "Alimento Balanceado",
    category: 'gato',
    brand : "Nutrique", 
    price : 3800,
    kg : 18,
    stock : 45,
    initial : 1, 
},
{
    id : 5,
    img: "../Keiko.jpg",
    title : "Alimento Balanceado",
    category: 'gato',
    brand : "Keiko", 
    price : 3200,
    kg : 20,
    stock : 90,
    initial : 1, 
},
{
    id : 6,
    img: "../NutriquePerro.jpg",
    title : "Alimento Balanceado",
    category: 'perro',
    brand : "Nutrique", 
    price : 58800,
    kg : 22,
    stock : 85,
    initial : 1, 

}]

export default mockProducts;